[package]
name = "xbench"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]

[dev-dependencies]
runnel = { path=".." }
criterion = { version = "0.8", default-features = false }
clf = "0.2"

[[bench]]
name = "bench-pipeio"
harness = false

[[bench]]
name = "bench-linepipeio"
harness = false
