[package]
name = "xbench"
version = "0.1.0"
edition = "2021"
rust-version = "1.60.0"

[dependencies]

[dev-dependencies]
runnel = { path=".." }
criterion = "0.7"
clf = "0.1"

[[bench]]
name = "bench-pipeio"
harness = false

[[bench]]
name = "bench-linepipeio"
harness = false
